### ISSUE TITLE
Component (+ child components) invisible in design tab

### ISSUE THREAD

**Issue by sebastian-jansson** [poirazis/bb-component-SuperTabs#3]
The supertabs component + any child components became invisible (_But still show up when previewing or publishing the app)_

Adding a new super-tab component does not help as it's also invisible:

![image](https://github.com/poirazis/bb-component-SuperTabs/assets/54795430/eddc5015-1417-4a1b-873a-561f0b0bd40d)

**Comment by poirazis** [comment]
Hey @sebastian-jansson 
Try not using the Super Tabs as a top level component. Wrap it inside a container.
Does that work ?

**Comment by poirazis** [comment]
Solved in v. 1.3.0
