### ISSUE TITLE
Feature suggestion: hide tab if child element is hidden

### ISSUE THREAD

**Issue by zedascouves** [poirazis/bb-component-SuperTabs#4]
User story:

- As a developer, I want to hide certain tabs from the users, so I can hide/show elements according to some conditions.

This is helpful, for example, to hide/show tabs according to user roles. Right now, using the condition feature, I can hide/show the child element, but the tab remains visible. It would be nice to hide/show it as well, according to the visibility of the child element.

**Comment by poirazis** [comment]
Hello @zedascouves will investigate how this can be implemented. 
Thank you for the suggestion.

**Comment by poirazis** [comment]
Implemented in version 1.3.0
