### ISSUE TITLE
TabIndex is always 0

### ISSUE THREAD

**Issue by kasgithub8** [poirazis/bb-component-SuperTabs#6]
Hi @poirazis,

I just used your super tabs because you can set a selected tab.
First, I tried the container name and then a number.

When I saw that neither had worked, I opened dev tools and saw that every container had the TabIndex 0.
Is this normal?

**Comment by poirazis** [comment]
HEy @kasgithub8 
If i understand correctly, the Tabindex is the Tab to be active on load, you cannot change the selected Tab by changing the property.

**Comment by kasgithub8** [comment]
Hi @poirazis,

yes. TabIndex should be the Tab that's active on load. But how do I set the super tabs component to tab 3 for example?
My understanding was that each of the containers you put inside the component, gets a TabIndex which you can use for the "On load".

If I'm wrong, could you tell me how to configure which tab is active on load?

**Comment by poirazis** [comment]
Hey @kasgithub8 
setting Active Tab Inder to 0 will load the first tab on load, 1 the second etc ... depending on their placement sequence
You may also want to try out the Super Container component, its the evolutions of the Super Tabs but can do many more stuff. https://github.com/poirazis/bb-component-SuperContainer

**Comment by kasgithub8** [comment]
Hi @poirazis,
You're right. So simple. Thank you!
